language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: wuKjAs98oPE0X0Hg1CdB3TedjMTm+I58YRUJkXYpJT0BKYODtFBQUx/nNMWTRdVcS2W7R9okaBrgLUCMusz9PKBsedNKduSZkdcdbfkHVb1Hcizfjl0pf8heeksgEwhmQwes4de8AzbBrzl+ReGP9IpXuKrEJmJC3MJrqdxsUkDDv3OZ5PjZ80Klsmr3dNhjuBZP8ZQSb4awrlgfc7LS6obPO03EQeDrRJOmb8ndOgrGLWPClsu+JXds5dje621ytMjwtHjcCcWPftnD72bDf2DmDbRYruSReLXf0nziFOgNrIeUBAB36IgJbQLM9C244yvlVEJsTijEiqYwWN5TmcZ3k1Q+IfkwEkltxdd6ERbGuJm2BEQjl00RLJr6CB0d6HYXHFzAet1Tw4dNcP1Z2Nio/cFZOcfz7DAZFcfd0q39uR3GZLXGYBYLrupFjIyR8dm8yuv6z7feQJAwEt8J3EXsoo6joyXqiN//QXr9CpRowL0+uBXtB9cEwW9uXO37f/wUTLHD5q0fwbrRcWb7NZM5yD3plCQ9pdCjOHRPqZgwmO1omGVuo/KN0NuuYzSTfFaAdaHJapzJiUUd8OPHKBGQliBD0X7bJDEjSbFXSr8xubyfsIReWrzV1BAidGRpGSR2g18+KhosKc41hPDpOR/KjHwQZgioytXB1opVn9U=
  app: serene-cliffs-93111
  on:
    repo: MARui22/projet
addons:
  code_climate:
    repo_token: d4692b22db65a230d7f24d3ec6d86ec3c02c873c3ea0f2a3c234b4b097d04d5b
    
after_success:
- bundle exec codeclimate-test-reporter
